name: SonarCloud Quality Gate
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          organization: ghulamhaider12
          projectKey: Ghulamhaider12_maqware-website
          projectName: 'maqware-website'
          scannerEnabled: true
          scannerVersion: latest
          extraProperties: |
            sonar.sources=src
            sonar.exclusions=**/*.test.js,**/node_modules/**
            sonar.tests=src
            sonar.test.inclusions=**/*.test.js
            sonar.javascript.lcov.reportPaths=coverage/lcov.info
            sonar.javascript.lcov.reportPaths=coverage/lcov-report/*.lcov
            sonar.coverage.exclusions=**/*.test.js
      - name: Check SonarCloud Quality Gate
        id: Quality Gate Status
        run: |
          quality_gate_status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: -X GET "https://sonarcloud.io/api/project_badges/quality_gate?project=Ghulamhaider12_maqware-website" | jq -r '.projectStatus.status')
          echo "SonarCloud Quality Gate Status: $quality_gate_status"
          echo "::set-output name=quality_gate_status::$quality_gate_status"

      - name: Prevent PR Merge
        if: steps.check_sonarcloud.outputs.quality_gate_status != 'PASSED'
        run: |
          echo "SonarCloud quality gate failed. Please fix the code quality issues before merging the pull request."
          exit 1
